# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         HTML-Table-Compiler
version:      0.01
version_from: Compiler.pm
installdirs:  site
requires:
    HTML::Table:                   

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.16
